config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :categories
  resources :budgets
  resources :expenses


  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/budget.rb
class Budget < ApplicationRecord
  has_many :categories
  has_many :users
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
    # render json: @budgets
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
    @budgets = Budget.find(params[:id])
    render json: @budgets
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:user_id, :category_id, :amount)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<%= form_with(model: budget, local: true) do |form| %>
  <% if budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :budget_user_id %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.number_field :category_id, id: :budget_category_id %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :budget_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Budgets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Category</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <td><%= budget.user_id %></td>
        <td><%= budget.category_id %></td>
        <td><%= budget.amount %></td>
        <td><%= link_to 'Show', budget %></td>
        <td><%= link_to 'Edit', edit_budget_path(budget) %></td>
        <td><%= link_to 'Destroy', budget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget', new_budget_path %>

app/views/budgets/new.html.erb
<h1>New Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Back', budgets_path %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @budget.user_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @budget.category_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @budget.amount %>
</p>

<%= link_to 'Edit', edit_budget_path(@budget) %> |
<%= link_to 'Back', budgets_path %>